# This is a basic workflow to help you get started with Actions

name: scrape
on:
  schedule:
     #* is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
  workflow_dispatch:
jobs:
  scrape-confessions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [3.6, 4.0, 4.2]
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Set up Python 3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install pip and npm dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Run scraper
        env:
          MDB_USERNAME: ${{ secrets.MDB_USERNAME }}
          MDB_PASSWORD: ${{ secrets.MDB_PASSWORD }}
        run: pipenv run python scraper.py
