# This is a basic workflow to help you get started with Actions

name: scrape
on:
 # schedule:
    # * is a special character in YAML so you have to quote this string
   # - cron:  '* * * * *'
  workflow_dispatch:
jobs:
  scrape-confessions:
    runs-on: ubuntu-latest
    steps:

      - name: Pipenv for Github Actions
        # You may pin to the exact commit or the version.
        # uses: VaultVulp/action-pipenv@0e0abc7839b234802947bb8aa1a7c7b8b00a2ff4
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          # pipenv command and its argument to be executed
          command: install
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        
      - name: Run Pipenv Shell
        # You may pin to the exact commit or the version.
        # uses: VaultVulp/action-pipenv@0e0abc7839b234802947bb8aa1a7c7b8b00a2ff4
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          # pipenv command and its argument to be executed
          command: shell
        
      - name: Run Script
        run: python scraper.py
