# This is a basic workflow to help you get started with Actions

name: auto-scrape
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * *'
jobs:
  scrape-confessions:
    runs-on: ubuntu-latest
    steps:

      - name: Pipenv for Github Actions
        # You may pin to the exact commit or the version.
        # uses: VaultVulp/action-pipenv@0e0abc7839b234802947bb8aa1a7c7b8b00a2ff4
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          # pipenv command and its argument to be executed
          command: pipenv install
          
      - name: Run Pipenv Shell
        run: pipenv shell
        
      - name: Run Script
        run: python scraper.py
        
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
